---
- name: Setup snapchain user with Oh My Zsh and Docker on Debian
  hosts: all
  become: yes
  vars:
    shared_user: snapchain
    sudo_group: sudo

  tasks:
    - name: Ensure required packages are installed
      apt:
        name:
          - build-essential # e.g. Make
          - ca-certificates # needed for Docker
          - curl
          - git
          - zsh
        state: present
        update_cache: yes

    - name: Ensure shared user exists and create it if not
      ansible.builtin.user:
        name: "{{ shared_user }}"
        groups: "{{ sudo_group }}"
        append: yes
        shell: /bin/zsh
        state: present

    - name: Ensure shared user has passwordless sudo
      lineinfile:
        path: /etc/sudoers
        regexp: "^{{ shared_user }} "
        line: "{{ shared_user }} ALL=(ALL) NOPASSWD:ALL"
        state: present
        validate: "visudo -cf %s"

    - name: Set up authorized keys for shared user
      authorized_key:
        user: "{{ shared_user }}"
        key: "{{ item }}"
      loop:
        - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCtCASsLB8vYFoT7/htiEvspM7WBxv4E5J5/TCYvzkHHj+NYguzs7YKv8ivh2zA15O/n313EzTYcLgccbRDU6icQLxoH4MmH7Q5CU2czja9FdC+Kn1erBaJjr7rFBc7cR0XSRyWsyoHg1yIF0yGJDgGgEeNVarJrx2fbRL7xGH2pvWzxrIXHEPHmaUUjMcZ7jCpp+x+dzMl7iZ/e/MgXg6MIGjM4ONp2Z7ndyxAI7RF2bt708znxHoJX0i/hfbkEUAAwM/G7iuyLkblB1SkNhLMcKGq3lVuEeVAl+zW1qiNq0hfXZURMNjUXzmfyjAz4GBDddZxhVFpSRSkJ0YuuerQ7zefdvdh7/G9aAiW8VbwJgGCzna2avMHOVoX7ZsphDyv+EQJk0blUgOlbINkJm/mELskUF4W2gqNFIcJq3wHh8ZEj3QV7+FzCoj75vAcm9yy1i5qE6LUr13xych5E9qSifD4OyDfQ0a0GW9iLmxcP8bBNv+dKoSrdRUXsa4FloM= zidong@snapchain.dev"
        - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDTliN+/C53s3pgw0omi80ofjCIx85twtkwR4YBPPvVZs2yNRK8AB01vOyafYv0XuY5fZzn0gU0z6bQYU1zAWMo1251LBc4eNrJrZC0B79/aDoYH/CaDvZPIOlsVckktwNg9pr/SP40oW4hLHpa7lvcCe0HX2PsXKszPls8CZMuK+ix33eoGvJHTVVO55kn709icgyh88lpsfvQ8FNM/hM58kT55q2HDNIrHxQCI0/mb08rv7QAylY4sel3CPvEWZD9RuSY7x7Di7OiDgROHSh1ok4/98XfTNdf+KAzzyJ7xIR4JLtFGV5BwJVjfnlKYjbY03HBizd/3y48mlY3Ijf7UoLe1I2ZDcsCjlhwj+Z53WCTQGgMA2DoLkmGN+r6UXwCf0lQGxKMBBHJxOvMepaVrKMsFWs0Qmgxi8yIB6PIsX5FDPf4ofSzIHHXidIzCE5yZ3rAV8Q7pFEsum41HZntHb50FYxZgvNa2vSEJrG2hwxRibRhSv4GbTR51pWKTLmBfIrHwC9SN+tvX9gETP+dq5LdXTRbuWjfrVh/HHsVXbugSpp4+0i5PVkoVVTYx2G7xzXi10z5WRHXEESKHp/AfshpYuPkTqVjQoj7556Sy5O9Aej8+t+rVLaSWSxSjV7gGXnkws7Ru5YOY51xOrKcrjQkHPkIw0S49Y0Kso4O0Q== yeungparkhay@gmail.com"
        - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDYaDaVoa/WKduRwe72jI13BlOKLWdOV32zJHK9K6Q0oDEuwfXUo5xqT1Lq5tblT8PfArT2GTvrAzRavB3usCk4kxyLFAaO2fsTsEJO0qU9QUTRczWu76L1aae2tIpn5YEosMiwHYFY3SVHhdt1NgrlQEiLtCVz2iGiC/hhThHCUuiSYg8Qc+CeDaMbIs0nTXPbFf2OWtAWlA9gIyyRvZp4etRWrUzC8qk55AJRiiVtwaFGgbkqf+TAr3wCiJh5vcufqFJWTAydPKtld3bJcRyB8QWqSaVIdDjrDX2T7WhDJ0YUHWdEpFcTPNxhxftaVfUeIqYTA4SuUKu2QRxQyBaB9axe1Ahujnact/5c8DYFhm0RD3tEsp9uNLny18K0uy3tCUIa3AGEFDVcNoFFEGtcz13f2cyFI53LbbBYMR/FjEo1r5+YE2nxyRcRTuMkjVIhj6WdSKsaeJ8bXz6kc+KPZfEBSPfMONOt9tKX9oWM/MfMSrEBsmEJsfIPp/yCA1Kxrr2T08QXvIKz4zASKBMaX0KbXjuWfwWjmJJXKumEkyK5nMVk7Rqaj31Eh9M3HXyGFaY7iCJ+z+ZncH/EAYiWFFkC57BjClJxG+/SnK24/mwCI6St5k5qy5Hm6FQVy9eDmFC1LqNPzaNjKrmj6JlQmTsdXzeTSR3YVTANxuXM0Q== fulfilself@gmail.com"

    - name: Disable password authentication
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^PasswordAuthentication"
        line: "PasswordAuthentication no"
      notify: Restart SSH

    - name: Install Oh My Zsh
      ansible.builtin.shell:
        cmd: sudo -u {{ shared_user }} sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
        creates: "/home/{{ shared_user }}/.oh-my-zsh"

    - name: Install Powerlevel10k theme
      ansible.builtin.git:
        repo: "https://github.com/romkatv/powerlevel10k.git"
        dest: "/home/{{ shared_user }}/.oh-my-zsh/custom/themes/powerlevel10k"
        version: master
        update: no

    - name: Set Powerlevel10k theme in .zshrc
      ansible.builtin.lineinfile:
        path: "/home/{{ shared_user }}/.zshrc"
        regexp: "^ZSH_THEME="
        line: 'ZSH_THEME="powerlevel10k/powerlevel10k"'

    - name: Copy Powerlevel10k config
      copy:
        src: "{{ playbook_dir }}/.p10k.zsh"
        dest: "/home/{{ shared_user }}/.p10k.zsh"
        owner: "{{ shared_user }}"
        group: "{{ shared_user }}"
        mode: "0644"

    - name: Ensure Powerlevel10k is sourced in .zshrc
      lineinfile:
        path: "/home/{{ shared_user }}/.zshrc"
        create: yes
        regexp: "^[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh"
        line: "[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh"
        owner: "{{ shared_user }}"
        group: "{{ shared_user }}"
        mode: "0644"

    - name: Create Docker GPG keyring directory
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"

    - name: Add Docker's official GPG key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/debian/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: "0644"

    - name: Add Docker repository
      ansible.builtin.shell:
        cmd: |
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
        creates: /etc/apt/sources.list.d/docker.list

    - name: Install Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        update_cache: yes

    - name: Add Snapchain user to Docker group
      ansible.builtin.user:
        name: "{{ shared_user }}"
        groups: docker
        append: yes
        state: present

  handlers:
    - name: Restart SSH
      service:
        name: sshd
        state: restarted
