---
- import_playbook: debian_server_setup_playbook.yml

- name: Setup the server for the op-babylon devnet
  hosts: all
  become: yes
  become_flags: -E
  environment:
    PATH: "{{ ansible_env.PATH }}:/home/{{ shared_user }}/.foundry/bin"

  vars:
    # TODO: this Go version requirement is external dependency. we should figure
    # out a way to keep it in sync or use docker to decouple this
    go_version: "1.22.6" # Match optimism/versions.json
    shared_user: snapchain # Ensure this matches the base playbook
    nvm_version: "0.40.1"
    node_version: "20.18.0"
    pnpm_version: "9.12.1"
    just_version: "1.34.0"
    foundry_version: "d28a3377e52e6a4114a8cea2903c115b023279e8"

  tasks:
    # TODO: this will fail if go is not installed
    - name: Check existing Go version
      ansible.builtin.command: /usr/local/go/bin/go version
      register: go_version_check
      ignore_errors: yes
      changed_when: false

    - name: Remove existing Go installation if version mismatch
      ansible.builtin.file:
        path: /usr/local/go
        state: absent
      when: go_version_check.rc != 0 or go_version not in go_version_check.stdout

    - name: Download and install Go if needed
      ansible.builtin.unarchive:
        src: "https://go.dev/dl/go{{ go_version }}.linux-amd64.tar.gz"
        dest: "/usr/local"
        remote_src: yes
      when: go_version_check.rc != 0 or go_version not in go_version_check.stdout

    - name: Set Go environment variables
      ansible.builtin.lineinfile:
        path: "/home/{{ shared_user }}/.zshrc"
        line: "export PATH=$PATH:/usr/local/go/bin"

    - name: Install NVM
      ansible.builtin.shell: >
        sudo -u {{ shared_user }} bash -c 'curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v{{ nvm_version }}/install.sh | bash'
      args:
        creates: "/home/{{ shared_user }}/.nvm/nvm.sh"

    # TODO: this step is not idempotent
    - name: Add NVM to .zshrc
      ansible.builtin.blockinfile:
        path: "/home/{{ shared_user }}/.zshrc"
        block: |
          export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm
          [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # Optional: bash completion

    # TODO: this step is not idempotent
    - name: Install Node.js using NVM
      ansible.builtin.shell: |
        . /home/{{ shared_user }}/.nvm/nvm.sh
        nvm install {{ node_version }}
        nvm alias default {{ node_version }}
      args:
        executable: /bin/bash

    # TODO: this step is not idempotent
    - name: Install pnpm
      ansible.builtin.shell: |
        curl -fsSL https://get.pnpm.io/install.sh | env PNPM_VERSION={{ pnpm_version }} sh -
      args:
        executable: /bin/bash

    - name: Install Foundryup
      ansible.builtin.shell: |
        sudo -u {{ shared_user }} zsh -c 'curl -L https://foundry.paradigm.xyz | zsh'
      args:
        executable: /bin/zsh
        creates: /home/{{ shared_user }}/.foundry/bin/foundryup

    - name: Check whether the Foundry binaries exist
      stat:
        path: '{{ item }}'
      loop:
        - /home/{{ shared_user }}/.foundry/bin/forge
        - /home/{{ shared_user }}/.foundry/bin/cast
        - /home/{{ shared_user }}/.foundry/bin/anvil
        - /home/{{ shared_user }}/.foundry/bin/chisel
      register: foundry_binaries_stat

    - name: Run Foundryup
      ansible.builtin.shell: |
        sudo -u {{ shared_user }} zsh -c 'foundryup -C {{ foundry_version }}'
      args:
        executable: /bin/zsh
      when: foundry_binaries_stat.results | rejectattr('stat.exists') | list

    - name: Install more dependencies
      ansible.builtin.apt:
        name:
          - jq
          - yq
          - netcat-openbsd
        state: present

    - name: Install just
      ansible.builtin.shell: |
        curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --to /usr/local/bin --tag {{ just_version }}
      args:
        creates: /usr/local/bin/just

    # Q: why is this needed?
    - name: enable SSH forwarding
      lineinfile:
        dest: /etc/sudoers
        insertafter: '^#?\s*Defaults\s+env_keep\b'
        line: 'Defaults    env_keep += "SSH_AUTH_SOCK"'
        state: present

    # this already initializes the submodules
    - name: Clone babylon OP devnet deployment repository
      ansible.builtin.git:
        repo: "git@github.com:Snapchain/op-chain-deployment.git"
        dest: "/home/{{ shared_user }}/op-chain-deployment"
        accept_hostkey: yes

    - name: Copy .env.example to .env
      ansible.builtin.copy:
        src: /home/{{ shared_user }}/op-chain-deployment/.env.example
        dest: /home/{{ shared_user }}/op-chain-deployment/.env
        remote_src: yes
        force: no

    # TODO: this fixes the unsafe directory error (wip)
    # fatal: [34.135.126.163]: FAILED! => {"msg": "Failed to set permissions on the temporary files Ansible needs to create when becoming an unprivileged user (rc: 1, err: chmod: invalid mode: ‘A+user:snapchain:rx:allow’\nTry 'chmod --help' for more information.\n}). For information on working around this, see https://docs.ansible.com/ansible-core/2.17/playbook_guide/playbooks_privilege_escalation.html#risks-of-becoming-an-unprivileged-user"}
    # - name: Set safe directory for git
    #   ansible.builtin.shell: |
    #     git config --global --add safe.directory /home/{{ shared_user }}/babylon-integration-deployment
    #   args:
    #     executable: /bin/bash
    #   become: yes
    #   become_user: "{{ shared_user }}"